#!/bin/sh
runuser -p app -c 'cd /home/app/decidim-ddgi && bin/delayed_job start'

# The following is simpler but sidekiq is executed as root and the files it creates are also created as root:root,
# this causes permissions problems when passenger tries to access files in tmp/ that were generated by sidekiq processes,
# mainly in /tmp/cache
#
# bin/delayed_job start