services:
  web:
    image: decidim-ddgi_app:latest
    container_name: decidim_ddgi_web
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - shared/storage:/var/www/decidim-ddgi/storage
      - shared/log:/var/www/decidim-ddgi/log
    environment:
      - PORT=3000
      - RAILS_ENV=production
    env_file:
      - decidim-ddgi.prod.env
    ports:
      # Puma listens to this port
      - '${WEB_PORT:-3000}:3000'
      # Puma connects to PostgreSQL through this port
      - '${POSTGRES_PORT:-5432}:${DB_PORT:-5432}'
      # SMTP through this port
      - '${SMTP_PORT:-587}:${MAILER_SMTP_PORT:-587}'
    command: bundle exec puma -C config/puma.rb
  worker:
    image: decidim-ddgi_app:latest
    container_name: decidim_ddgi_worker
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - shared/storage:/var/www/decidim-ddgi/storage
      - shared/log:/var/www/decidim-ddgi/log
    environment:
      - RAILS_ENV=production
    env_file:
      - decidim-ddgi.prod.env
    ports:
      # Connect to PostgreSQL through this port
      - '${POSTGRES_PORT:-5432}:${DB_PORT:-5432}'
      # SMTP through this port
      - '${SMTP_PORT:-587}:${MAILER_SMTP_PORT:-587}'
    command: bin/delayed_job start &
