default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  min_messages: notice
  database: "decidim_diputacio_girona_development"

test:
  <<: *default
  pool: <%= ENV.fetch('DB_POOL') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { "localhost" } %>
  database: "decidim_diputacio_girona_custom_test"
  username: <%= ENV.fetch('DB_USERNAME') { "" } %>
  password: <%= ENV.fetch('DB_PASSWORD') { "" } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>

integration:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
