default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>

development:
  <<: *default
  min_messages: notice
  database: <%= ENV.fetch("DB_DATABASE") { "decidim_diputacio_girona_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME") { "decidim_diputacio_girona_test" } %>

integration:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE") { "decidim_diputacio_girona_development" } %>
  # url: <%= ENV['DATABASE_URL'] %>