# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  geocoder:
    here_api_key: <%= ENV["HERE_API_KEY"] %>

development:
  <<: *default
  secret_key_base: another_long_secret_key_base_that_will_be_used_in_development
  geocoder:
    here_api_key: 'fakekey'

test:
  <<: *default
  secret_key_base: a_very_long_and_possibly_redundant_grammatically_speaking_secret_key_base_but_hey_it_is_needed
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true
  geocoder:
    here_api_key: 'fakekey'

integration:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
  smtp_username: <%= ENV["MAILER_SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["MAILER_SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["MAILER_SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["MAILER_SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["MAILER_SMTP_PORT"] %>
  smtp_starttls_auto: true
  smtp_authentication: "plain"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
  smtp_username: <%= ENV["MAILER_SMTP_USER_NAME"] || ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["MAILER_SMTP_PASSWORD"] || ENV["SENDGRID_PASSWORD"] %>
  smtp_address: <%= ENV["MAILER_SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_domain: <%= ENV["MAILER_SMTP_DOMAIN"] || "decideix.com" %>
  smtp_port: <%= ENV["MAILER_SMTP_PORT"] || "587" %>
  smtp_starttls_auto: true
  smtp_authentication: "plain"
