name: "[CI] Decidim"
on: [push]

env:
  RUBY_VERSION: 3.0.2
  NODE_VERSION: 16.9.1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis:3.2-alpine
        ports: ["6379:6379"]
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
    steps:
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 119.0.6045.105

      - name: List Chrome
        shell: "bash"
        run: apt list --installed | grep chrome

      - name: Remove Chrome
        shell: "bash"
        run: sudo apt remove google-chrome-stable

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 119.0.6045.105
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install

      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-app-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-app-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-app-rubydeps-

      - name: Install Ruby deps
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: bundle install --jobs 4 --retry 3

      - name: Generate test_app
        run: |
          RAILS_ENV=test bundle exec rails db:create
          RAILS_ENV=test bundle exec rails db:migrate

      - name: Run RSpec
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: CI=1 RAILS_ENV=test bundle exec rspec --backtrace
