name: "[CI] Decidim"
on: [push]

env:
  RUBY_VERSION: 3.3.10
  NODE_VERSION: 18.17.1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis:3.2-alpine
        ports: ["6379:6379"]
    env:
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: decidim_diputacio_girona_test
      DB_POOL: "5"
      SECRET_KEY_BASE: dummy_secret_key_base
      MAILER_SMTP_ADDRESS: "smtp.example.com"
      MAILER_SMTP_DOMAIN: "example.com"
      MAILER_SMTP_PORT: "587"
      MAILER_SMTP_USER_NAME: "user"
      MAILER_SMTP_PASSWORD: "password"
      GEOCODER_LOOKUP_APP_ID: "dummy_app_id"
      GEOCODER_LOOKUP_APP_CODE: "dummy_app_code"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install

      - name: Recover Ruby dependency cache
        uses: actions/cache@v3
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-app-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-app-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-app-rubydeps-

      - name: Install Ruby deps
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: bundle install --jobs 4 --retry 3

      - name: List Chrome
        shell: "bash"
        run: apt list --installed | grep chrome

      - name: Remove Chrome
        shell: "bash"
        run: sudo apt remove google-chrome-stable

      - name: Install ImageMagick
        shell: "bash"
        run: sudo apt install imagemagick

      - name: Generate test_app
        run: |
          RAILS_ENV=test bundle exec rails db:create
          PGPASSWORD=${{ env.DB_PASSWORD }} psql -h ${{ env.DB_HOST }} -U ${{ env.DB_USERNAME }} -d ${{ env.DB_DATABASE }} -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
          RAILS_ENV=test bundle exec rails db:migrate

      - name: Run RSpec
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: CI=1 RAILS_ENV=test bundle exec rspec --backtrace
